---
name: Scheduled Security Scan

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  security:
    uses: miikkak/workflows/.github/workflows/security-scan.yml@88499bae26c81d34d780bb1f8659aab4faf05865 # main
    secrets: inherit
