---
name: Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:


permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    uses: miikkak/workflows/.github/workflows/super-linter.yml@88499bae26c81d34d780bb1f8659aab4faf05865 # main
    secrets: inherit
    with:
      validate-bash: false
      validate-json: true
